export const ParamsNames = {
    dt: "Δt, ч",
    dr: "Δr, мм",
    t_max: "t<sub>max</sub>, ч",
    sigma_0: "σ<sup>0</sup>, МПа",
    tau_max: "τ<sub>max</sub>, МПа",
    q: "q, МПа",
    R1: "R<sub>1</sub>, мм",
    R2: "R<sub>2</sub>, мм",
    E: "E, МПа",
    mu: "μ",
    b: "b",
    n: 'n',
    lambda: 'λ',
    mu_1: 'μ<sub>1</sub>',
    m: 'm',
    c_p: 'c, (МПа)<sup>-m</sup> &nbsp; ч<sup>-1</sup>',
    alpha1_p: 'α<sub>1</sub>, (МПа)<sup>-m<sub>α</sub>-1</sup>',
    mAlpha_p: 'mα',
    A1_p: 'A<sub>1</sub>, (МПа)<sup>m<sub>A</sub>-1</sup>',
    mA_p: 'mA'
}